#cloud-config

package_update: true
package_upgrade: true

users:
  - name: ${admin_username}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    ssh_authorized_keys:
      - ${admin_ssh_public_key}
  - name: ${username}
    groups: users
    ssh_authorized_keys:
      - ${ssh_public_key}

write_files:
  - encoding: b64
    content: ${install_tools_script}
    path: /usr/local/bin/tap-workshop-builder-scripts/install-tools.sh
    permissions: "0755"
  - encoding: b64
    content: ${login_script}
    path: /usr/local/bin/tap-workshop-builder-scripts/login.sh
    permissions: "0755"
  - encoding: b64
    content: ${clone_and_setup_tap_made_simple_script}
    path: /usr/local/bin/tap-workshop-builder-scripts/clone-and-setup-tap-made-simple.sh
    permissions: "0755"

runcmd:
  - /usr/local/bin/tap-workshop-builder-scripts/install-tools.sh
  - |
    su - ${username} << EOM
      AZURE_SERVICE_PRINCIPAL_CLIENT_ID="${azure_service_principal_client_id}" \
        AZURE_SERVICE_PRINCIPAL_CLIENT_SECRET="${azure_service_principal_client_secret}" \
        AZURE_TENANT_ID="${azure_tenant_id}" \
        TANZU_NETWORK_REFRESH_TOKEN="${tanzu_network_refresh_token}" \
        /usr/local/bin/tap-workshop-builder-scripts/login.sh
    EOM
  - |
    su - ${username} << EOM
      USERNAME="${username}" \
        USER_RESOURCE_GROUP="${azure_user_resource_groups_prefix}-${username}" \
        TANZU_REGISTRY_USERNAME="${tanzu_registry_username}" \
        TANZU_REGISTRY_PASSWORD="${tanzu_registry_password}" \
        DNS_ZONE_NAME="${dns_zone_name}" \
        DNS_ZONE_RESOURCE_GROUP="${dns_zone_resource_group}" \
        /usr/local/bin/tap-workshop-builder-scripts/clone-and-setup-tap-made-simple.sh
    EOM
